# Generated by Django 4.2 on 2026-06-17 08:45

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('AGENT', 'Agent DGI'), ('CONTRIBUABLE', 'Contribuable')], default='CONTRIBUABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'T_Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='AgentDGI',
            fields=[
                ('id_agent', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom_complet', models.CharField(max_length=255)),
                ('fonction', models.CharField(blank=True, max_length=100)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'T_Agent_DGI',
            },
        ),
        migrations.CreateModel(
            name='Contribuable',
            fields=[
                ('id_contribuable', models.AutoField(primary_key=True, serialize=False)),
                ('raison_sociale', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'Identification Fiscale")),
                ('adresse_physique', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribuable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'T_Contribuable',
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id_declaration', models.AutoField(primary_key=True, serialize=False)),
                ('mois_fiscal', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')])),
                ('annee_fiscale', models.IntegerField()),
                ('base_imposable', models.DecimalField(decimal_places=2, help_text='Total des rémunérations brutes en CDF', max_digits=15)),
                ('taux_iper', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Taux IPER en %', max_digits=5)),
                ('montant_iper', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('penalite_retard', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validée'), ('REJETE', 'Rejetée'), ('GELE', 'Gelée')], default='EN_ATTENTE', max_length=20)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('agent_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_validees', to='iper_app.agentdgi')),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='iper_app.contribuable')),
            ],
            options={
                'db_table': 'T_Declaration',
                'ordering': ['-date_soumission'],
                'unique_together': {('contribuable', 'mois_fiscal', 'annee_fiscale')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mode_paiement', models.CharField(choices=[('VIREMENT', 'Virement bancaire'), ('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Chèque')], max_length=20)),
                ('reference_quittance', models.CharField(max_length=100, unique=True)),
                ('banque', models.CharField(blank=True, max_length=100)),
                ('observations', models.TextField(blank=True)),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paiement', to='iper_app.declaration')),
            ],
            options={
                'db_table': 'T_Paiement',
            },
        ),
    ]
